---
title: "figures"
author: "J Coetsee - 19491050"
date: "22/01/2022"
output: html_document
---

```{r setup, include=FALSE}
rm(list =ls())
gc()
# Open/install required packages
#################################################
lop <- c("raster", "RColorBrewer", "rgdal", "tictoc", "rgeos", "foreach", "doSNOW", "stringr","dplyr",
         "sp", "parallel", "ggplot2", "randomForest", "plm", "glmnet",
         "foreign", "tree", "gbm","fasterize","sf","caret")
newp <- lop[!(lop %in% installed.packages()[,"Package"])]
if(length(newp)) install.packages(newp)
lapply(lop, require, character.only = TRUE)
rasterOptions(progress= "text", timer =T)

```


```{r}
### Read in Tif files from thesis wd:
# open prepared data
avg <- raster(paste0("C:/Projects/Masters-Thesis-2021/data/downloaded/nightlight/avg/F182011.v4c_web.avg_vis.tif"))
pct <- raster(paste0("C:/Projects/Masters-Thesis-2021/data/downloaded/nightlight/pct/F182011.v4c.avg_lights_x_pct.tif"))
lma <- raster(paste0("C:/Projects/Masters-Thesis-2021/data/prepared/nightlight/local_variables/lm_freq_5_f182011.tif"))
lmb <- raster(paste0("C:/Projects/Masters-Thesis-2021/data/prepared/nightlight/local_variables/lm_avg_25_f182011.tif"))
lmc <- raster(paste0("C:/Projects/Masters-Thesis-2021/data/prepared/nightlight/local_variables/lm_freq_99_f182011.tif"))
lmd <- raster(paste0("C:/Projects/Masters-Thesis-2021/data/prepared/nightlight/local_variables/lm_avg_199_f182011.tif"))
lme <- raster(paste0("C:/Projects/Masters-Thesis-2021/data/prepared/nightlight/local_variables/local_noise_f182011.tif"))
lmf <- raster(paste0("C:/Projects/Masters-Thesis-2021/data/prepared/nightlight/local_variables/local_detections_f182011.tif"))
bui <- raster(paste0("C:/Projects/Masters-Thesis-2021/data/prepared/builtup/built_2011.tif"))

#shapefile to crop to 

shpSA <- readOGR("C:/SARB/Truck-o-Meter/Truck-o-Meter/data/shapefile/gadm36_ZAF_0.shp")
shpSA <- spTransform(shpSA, crs(avg))

avg_stack=stack(avg_mask)
pct_stack=stack(pct)
#then plot it an RGB raster
plotRGB(avg_stack)
plotRGB(pct_stack)

plot(avg)
plot(pct)

# match extent of the input raster images
avg = crop(avg,extent(shpSA))
avg_mask = mask(avg, shpSA)
pct = crop(pct,extent(shpSA))
pct_mask = mask(pct, shpSA)
lma = crop(lma,extent(shpSA))
lma_mask = mask(lma, shpSA)
lmb = crop(lmb,extent(shpSA))
lmb_mask = mask(lmb, shpSA)
lmc = crop(lmc,extent(shpSA))
lmc_mask = mask(lmc, shpSA)
lmd = crop(lmd,extent(shpSA))
lmd_mask = mask(lmd, shpSA)
lme = crop(lme,extent(shpSA))
lme_mask = mask(lme, shpSA)
lmf = crop(lmf,extent(shpSA))
lmf_mask = mask(lmf, shpSA)
bui = crop(bui,extent(shpSA))
bui_mask = mask(bui, shpSA)

my.palette <- brewer.pal(n = 20, name = "OrRd")
projection(avg_mask) <- "+proj=longlat +datum=WGS84 +no_defs"


#stable 

stable <- raster(paste0("C:/Projects/Masters-Thesis-2021/data/Nightlight/F182011.v4/F182011.v4c_web.stable_lights.avg_vis.tif"))
stable_crop <- crop(stable, shpSA)
stable_mask <- mask(stable_crop, shpSA)
    
stable_stack=stack(stable_mask)
plotRGB(stable_stack, 2,1)

plot(shpSA)
plot(stable_stack, add = T)

raster_brick <- brick(lma_mask,lmb_mask,lmc_mask,lmd_mask,lme_mask,lmf_mask)
plot(raster_brick, legend = F, box = F, axes = F)


plot(stable_mask)
plot(shpSA, add= T)
stable_mask[stable_mask < 6] <- 0.1
plot(stable_mask)
plot(shpSA, add= T)
# Final Images

final <- raster(paste0(" C:/Projects/Masters-Thesis-2021/data/final_products/Local_Human_Lights_f182011.tif"))
final_crop <- crop(final, shpSA)
final_mask <- mask(final_crop, shpSA)
final_stack=stack(final_mask)
plotRGB(final_stack)

plot(avg_mask)
plot(final_mask, box = F)
plot(shpSA, add = T)



```

