---
output:
  md_document:
    variant: markdown_github
---

# Purpose

The aim of this README is to explain the various files and data sets that make up this Advanced Cross Section Econometrics project, which forms part of my masters degree.

The project is based around filtering out noise in the DMSP-OLS night lights data sets for 2001 and 2011. The methodology entails filtering out non-human generated light by employing a random forest algorithm and complementary remote sensing data sets. DMSP-OLS is often very noisy in the lower end of the light-spectrum, leading to many researchers dropping out those values entirely, thereby losing a large amount of data. 

Specifically, I employ the methodology prescribed by Määttä and Lessmann (2019) in 'Human lights', published in Remote Sensing, 11(19). The project utilises AWS cloud computing and Rstudio Server due to the large memory-burden of the data, with the results intended for use in my Masters Thesis. 


The following files and directories are of import:

* wrangling_cs - cleaning and exploratory analysis
* 
* 
* 
* Write_up folder- where the final project is written up and compiled



### Notes from readings:

----
Income Poverty at Small Area Level in
South Africa in 2011
Michael Noble, Wanga Zembe, Gemma Wright, David
Avenell and Stefan Noble 
----

"
In order to produce a ward level measure it is necessary to derive information from the
2011 census as no survey source is reliable for such small areas. Achieving this measure
utilising census data obtained using Superstar requires a number of complex data
manipulations. In brief, the banded household income (which is itself a derived variable
being the aggregate of individual banded income) needs to be translated into point
income and a per capita income created. This can then be compared to each of the
poverty lines and proportions of individuals falling below the lines for each ward
computed. Necessarily there is some loss of information when the banded income is
translated into point income. To do this the same procedure that Stats SA used when
creating the banded household income from banded individual income is utilised.
Basically, the logarithmic mean of the band was employed to specify the particular point
income value for the band.  " (4)

----
Dieter:
----

Jy sou ‘n small area estimation kon doen met hierdie data.

Jy sou eers moet werk met die census micro data:
https://www.dropbox.com/s/uskxfjjdh8djk2t/Census2011_10pct.dta?dl=0


Dan in STATA (jammer!) so iets:

recode education (13=10) (14=11)      (15=12) (19 20=11) (16 17 18 21 22 23 = 13) (98=0) (25=15) (27 26 =16) (24 28=17) (29=.), gen(educ)

     *Keep only working age individuals who are employed

keep if age>=15 & age<=65 & status1==1

     *Use multiple imputation to impute missings (which in this data represent “No income”- known to be overreported in census data and “Unspecified”)

mi set wide

mi impute intreg l_inc educ c.age##c.age i.area i.race i.sex  [pweight = pweight] , add(10) replace double by(muni) ll(l_inc_low) ul(l_inc_up) force

mi estimate , saving(muniincome, replace): reg l_inc  educ c.age##c.age i.area i.race i.sex  i.muni [pweight = pweight]

 
Dan moet jy gaan na jou ward-level data van supercross. Jy gaan dit moet uitbrei. Alle veranderlikes wat jy in die imputation regressie het, moet ook jou kolomme afbreek (maw elke income-age-educ combination binne elke ward). Jy gaan daardie data moet aflaai en reshape om te lyk soos die micro data.

 

Dan predict jy incomes per individue binne elke ward (gebruik jou estimates op die ward-level data)

 

mi predictnl ln_y = predict(xb) using muniincome, ci(ci_low ci_up)

 

Tegnies is hierdie nie ‘n volledige procedure nie. Die rede hiervoor is dat daar is variansie binne wards wat ons nie optel nie, en ons estimate nie ‘n “within-ward” variance nie. As jy die werk oor poverty mapping lees, sal jy agterkom jy moet dit doen. Dit is egter nie moontlik met die census data nie, ongelukkig.



